version: '3.7'

services:
  frontend:
    container_name: bedo-frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
    image: senyorjou/bedo-frontend
    ports:
      - 3000:3000
  backend:
    container_name: bedo-backend
    build:
      context: backend/
      dockerfile: Dockerfile
    image: senyorjou/bedo-backend
    ports:
      - 3030:3030
