# pull official base image
FROM node:13.12.0-alpine

# set working directory
RUN mkdir /app
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# add app
COPY . ./

# install
RUN npm install
RUN npm install react-scripts@3.4.1 -g

# start app
CMD ["npm", "start"]
