FROM node:latest


ARG VERSION="1.0"
ARG APP_ROOT="/app"

LABEL maintainer="demo team @ userzoom"
LABEL version=$VERSION


RUN mkdir -p ${APP_ROOT}

COPY . ${APP_ROOT}

RUN cd ${APP_ROOT} && sleep 10 && npm install

CMD ["node", "app/src/index.js"]
