FROM clojure as builder

WORKDIR /app

COPY project.clj .

RUN lein deps

COPY . .

RUN mv "$(lein uberjar | sed -n 's/^Created \(.*standalone\.jar\)/\1/p')" app.jar

FROM gcr.io/distroless/java11-debian11
WORKDIR /app

COPY --from=builder /app/app.jar ./app.jar

CMD ["app.jar"]
